name: Build Utilities

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '14.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install -U jupyterlab~=3.0 jupyter_packaging~=0.7.9 pip
        jlpm
        jlpm run build
    - name: Patch Release
      run: |
        jlpm release:patch --force
    - name: Minor Release
      run: |
        jlpm release:bump minor --force
    - name: Major Release
      run: |
        jlpm release:bump major --force
